# Generated by Django 4.2.3 on 2024-01-11 01:04

from django.db import migrations, models
import utils.custom_id


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_id_alter_location_ward_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.CharField(default=utils.custom_id.district_custom_id, editable=False, max_length=17, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='id',
            field=models.CharField(default=utils.custom_id.province_custom_id, editable=False, max_length=17, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='id',
            field=models.CharField(default=utils.custom_id.ward_custom_id, editable=False, max_length=17, primary_key=True, serialize=False, unique=True),
        ),
    ]
