# Generated by Django 4.2.3 on 2024-01-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_district_id_alter_province_id_alter_ward_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
