# Generated by Django 4.2.3 on 2024-01-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_district_id_alter_province_id_alter_ward_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='administrative_unit_id',
            new_name='AdministrativeUnit',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='province_id',
            new_name='Province',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='ward_id',
            new_name='Ward',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='administrative_region_id',
            new_name='AdministrativeRegion',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='administrative_unit_id',
            new_name='AdministrativeUnit',
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='administrative_unit_id',
            new_name='AdministrativeUnit',
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='district_id',
            new_name='District',
        ),
    ]
