# Generated by Django 4.2.3 on 2024-01-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_location_location_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='administrative_unit_id',
            new_name='administrative_unit',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='province_id',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='ward_id',
            new_name='ward',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='administrative_region_id',
            new_name='administrative_region',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='administrative_unit_id',
            new_name='administrative_unit',
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='administrative_unit_id',
            new_name='administrative_unit',
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='district_id',
            new_name='district',
        ),
    ]
