# Generated by Django 4.2.3 on 2024-01-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_location_location_name'),
        ('location', '0006_location_latitude_location_longitude'),
    ]

    operations = [
    ]
