# Generated by Django 4.2.8 on 2023-12-20 04:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=100)),
                ('code_name_en', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('full_name_en', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('short_name_en', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=100)),
                ('code_name_en', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('rental_date', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('depth', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('virtual_cabinet_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CabinetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('type_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=100)),
                ('cost_per_unit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(blank=True, default=None, null=True)),
                ('time_end', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('hash_code', models.CharField(max_length=100)),
                ('is_assigned', models.CharField(max_length=100)),
                ('cell_index', models.CharField(max_length=100)),
                ('depth', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('cabinetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='CostVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('from_hour', models.FloatField()),
                ('to_hour', models.FloatField()),
                ('cost', models.FloatField()),
                ('unit', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('full_name_en', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=100)),
                ('administrativeUnitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.administrativeunit')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=100)),
                ('total_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('full_name_en', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=100)),
                ('administrativeUnitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.administrativeunit')),
                ('districtId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.district')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('full_name_en', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=100)),
                ('administrativeRegionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.administrativeregion')),
                ('administrativeUnitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.administrativeunit')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=100)),
                ('time_start', models.DateTimeField(blank=True, default=None, null=True)),
                ('time_end', models.DateTimeField(blank=True, default=None, null=True)),
                ('sub_total', models.FloatField()),
                ('cellId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cell')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_detail', models.CharField(max_length=100)),
                ('wardId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ward')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='provinceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.province'),
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kafka_id', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.location')),
            ],
        ),
        migrations.CreateModel(
            name='CellLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('cellId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cell')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=100)),
                ('cabinet_id', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('cabinetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cabinet')),
                ('campaignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='costVersionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.costversion'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='cabinetTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cabinettype'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='controllerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.controller'),
        ),
    ]
