# Generated by Django 4.2.8 on 2023-12-20 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_custom_email_cabinet_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='cost_version_id',
        ),
        migrations.AddField(
            model_name='cabinet',
            name='cabinetTypeId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.cabinettype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cabinet',
            name='controllerId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.controller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='costVersionId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.costversion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigncabinet',
            name='cabinetId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.cabinet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigncabinet',
            name='campaignId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.campaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cell',
            name='cabinetId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.cabinet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celllog',
            name='cellId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.cell'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controller',
            name='locationId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='administrativeUnitId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.administrativeunit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='provinceId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='wardId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.ward'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='cellId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.cell'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='orderId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='userId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='administrativeRegionId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.administrativeregion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='administrativeUnitId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.administrativeunit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='administrativeUnitId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.administrativeunit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='districtId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.district'),
            preserve_default=False,
        ),
    ]
