# Generated by Django 4.2.8 on 2023-12-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_campaign_cost_version_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='time_end',
            field=models.DateTimeField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='time_start',
            field=models.DateTimeField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='time_end',
            field=models.DateTimeField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='time_start',
            field=models.DateTimeField(verbose_name=''),
        ),
    ]
