# Generated by Django 4.2.8 on 2023-12-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_campaign_time_end_alter_campaign_time_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='time_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='time_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='time_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='time_start',
            field=models.DateTimeField(),
        ),
    ]
