# Generated by Django 4.2.3 on 2024-01-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_cell_expired_date_alter_cell_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='hash_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
