# Generated by Django 4.2.3 on 2024-01-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_cell_expired_date_alter_cell_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabinet',
            old_name='cabinetType_id',
            new_name='cabinet_type',
        ),
        migrations.RenameField(
            model_name='cabinet',
            old_name='controller_id',
            new_name='controller',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='cost_version_id',
            new_name='cost_version',
        ),
        migrations.RenameField(
            model_name='campaigncabinet',
            old_name='cabinet_id',
            new_name='cabinet',
        ),
        migrations.RenameField(
            model_name='campaigncabinet',
            old_name='campaign_id',
            new_name='campaign',
        ),
        migrations.RenameField(
            model_name='cell',
            old_name='cabinet_id',
            new_name='cabinet',
        ),
        migrations.RenameField(
            model_name='celllog',
            old_name='cell_id',
            new_name='cell',
        ),
        migrations.RenameField(
            model_name='celllog',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='controller',
            old_name='location_id',
            new_name='location',
        ),
    ]
