# Generated by Django 4.2.3 on 2024-01-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_rename_cabinettype_id_cabinet_cabinet_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cost_version',
            field=models.CharField(default='UNUSABLE', max_length=100),
        ),
        migrations.AlterField(
            model_name='cell',
            name='hash_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
