# Generated by Django 4.2.3 on 2024-01-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_alter_campaign_cost_version_alter_cell_hash_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costversion',
            name='unit',
            field=models.DurationField(),
        ),
    ]
