# Generated by Django 4.2.3 on 2024-01-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_alter_costversion_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costversion',
            name='to_hour',
            field=models.FloatField(null=True),
        ),
    ]
