# Generated by Django 4.2.3 on 2024-01-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0007_alter_campaigncabinet_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='virtual_cabinet_id',
        ),
        migrations.RemoveField(
            model_name='cabinettype',
            name='cost_per_unit',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='expired_date',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='user_id',
        ),
        migrations.AddField(
            model_name='cabinet',
            name='column_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='row_number',
            field=models.IntegerField(default=1),
        ),
    ]
