# Generated by Django 4.2.3 on 2024-01-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0008_remove_cabinet_virtual_cabinet_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='hash_code',
            field=models.CharField(default='101495be-66b3-452a-a4d9-14571b7eee95', max_length=100, unique=True),
        ),
    ]
