# Generated by Django 4.2.3 on 2024-01-22 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0009_alter_cell_hash_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='hash_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
