# Generated by Django 4.2.3 on 2024-01-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0010_alter_cell_hash_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='name',
            field=models.CharField(blank=True, default='cabinet', max_length=200),
        ),
    ]
