# Generated by Django 4.2.3 on 2024-01-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0011_cabinet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='image_link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cabinettype',
            name='image_link',
            field=models.CharField(max_length=500),
        ),
    ]
