# Generated by Django 4.2.3 on 2024-03-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0012_alter_cabinet_image_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='kafka_id',
        ),
        migrations.RemoveField(
            model_name='controller',
            name='topic',
        ),
    ]
