# Generated by Django 4.2.3 on 2024-01-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
