# Generated by Django 4.2.8 on 2023-12-26 14:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('total_amount', models.FloatField()),
                ('payment_method', models.PositiveSmallIntegerField()),
                ('order_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField()),
                ('time_start', models.DateTimeField(blank=True, default=None, null=True)),
                ('time_end', models.DateTimeField(blank=True, default=None, null=True)),
                ('sub_total', models.FloatField()),
                ('cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.cell')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
