# Generated by Django 4.2.3 on 2024-01-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deleted',
        ),
    ]
