# Generated by Django 4.2.3 on 2024-01-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='cell_id',
            new_name='cell',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='user_id',
            new_name='user',
        ),
    ]
