# Generated by Django 4.2.3 on 2024-01-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_order_id_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='campaign_id',
        ),
    ]
