name: Delete Branch

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          git fetch --all
          git branch -d ${{ github.event.pull_request.head.ref }}
          git push origin --delete ${{ github.event.pull_request.head.ref }}
